language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t mariasurgan/react-test -f ./client/Dockerfile.dev ././client

script:
  - docker run -e CI=true mariasurgan/react-test npm test

after_success: 
  - docker build -t mariasurgan/multi-client ./client
  - docker build -t mariasurgan/multi-nginx ./nginx
  - docker build -t mariasurgan/multi-server ./server
  - docker build -t mariasurgan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mariasurgan/multi-client
  - docker push mariasurgan/multi-nginx
  - docker push mariasurgan/multi-server
  - docker push mariasurgan/multi-worker